"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.$HDSPResult = exports.$HDSPResponse = exports.$HDSPRequest = exports.$HDSPModeErrors = exports.$HardwareVersion = exports.$HAMPVelocityPercentResponse = exports.$HAMPVelocityPercent = exports.$HAMPStopResponse = exports.$HAMPState = exports.$HAMPStartResponse = exports.$HAMPResponse = exports.$HAMPModeErrors = exports.$GenericResultResponse = exports.$GenericResult = exports.$GenericError = exports.$FixedPos = exports.$FirmwareVersion = exports.$FirmwareStatus = exports.$ErrorResponse = exports.$Duration = exports.$ConnectionKey = exports.$ConnectedResponse = exports.$Connected = exports.$Branch = exports.$BASEModeErrors = exports.UpdateStatusResponse = exports.StateResult = exports.SlideResult = exports.ModeUpdateResponse = exports.Model = exports.Mode = exports.MAINTENANCEModeErrors = exports.HSSPState = exports.HSSPSetupResult = exports.HSSPPlayResult = exports.HSSPModeErrors = exports.HDSPResult = exports.HDSPModeErrors = exports.HAMPState = exports.HAMPModeErrors = exports.GenericResult = exports.FirmwareStatus = exports.Branch = exports.BASEModeErrors = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.handyApi = void 0;
exports.$UpdatePerform = exports.$Timestamp = exports.$SyncResponse = exports.$SyncCount = exports.$StatusResponse = exports.$StateResult = exports.$SlideUpdateResponse = exports.$SlideSettings = exports.$SliderMinResponse = exports.$SliderMaxResponse = exports.$SlideResultResponse = exports.$SlideResult = exports.$SlideResponse = exports.$Sha256 = exports.$Setup = exports.$SettingsResponse = exports.$SessionId = exports.$ServerTimeResponse = exports.$RPCResult = exports.$PositionAbsoluteResponse = exports.$PositionAbsolute = exports.$PercentValue = exports.$Outliers = exports.$OtaLatestResponse = exports.$OtaLatest = exports.$OffsetUpdate = exports.$OffsetResponse = exports.$Offset = exports.$NextXPVP = exports.$NextXPVA = exports.$NextXPT = exports.$NextXAVA = exports.$NextXAT = exports.$ModeUpdateResponse = exports.$ModeUpdate = exports.$Model = exports.$Mode = exports.$MAINTENANCEModeErrors = exports.$LoopSettingUpdate = exports.$LoopSettingResponse = exports.$Looping = exports.$InfoResponse = exports.$HSSPState = exports.$HSSPSetupResult = exports.$HSSPResponse = exports.$HSSPPlayResult = exports.$HSSPPlayResponse = exports.$HSSPPlay = exports.$HSSPModeErrors = exports.$HDSPTimeRequest = void 0;
exports.TimesyncService = exports.SlideService = exports.OtaService = exports.MaintenanceService = exports.HstpService = exports.HsspService = exports.HdspService = exports.HampService = exports.BaseService = exports.$VelocityAbsolute = exports.$Url = exports.$UpdateStatusResponse = void 0;
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var handyApi_1 = require("./handyApi");
Object.defineProperty(exports, "handyApi", { enumerable: true, get: function () { return handyApi_1.handyApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var BASEModeErrors_1 = require("./models/BASEModeErrors");
Object.defineProperty(exports, "BASEModeErrors", { enumerable: true, get: function () { return BASEModeErrors_1.BASEModeErrors; } });
var Branch_1 = require("./models/Branch");
Object.defineProperty(exports, "Branch", { enumerable: true, get: function () { return Branch_1.Branch; } });
var FirmwareStatus_1 = require("./models/FirmwareStatus");
Object.defineProperty(exports, "FirmwareStatus", { enumerable: true, get: function () { return FirmwareStatus_1.FirmwareStatus; } });
var GenericResult_1 = require("./models/GenericResult");
Object.defineProperty(exports, "GenericResult", { enumerable: true, get: function () { return GenericResult_1.GenericResult; } });
var HAMPModeErrors_1 = require("./models/HAMPModeErrors");
Object.defineProperty(exports, "HAMPModeErrors", { enumerable: true, get: function () { return HAMPModeErrors_1.HAMPModeErrors; } });
var HAMPState_1 = require("./models/HAMPState");
Object.defineProperty(exports, "HAMPState", { enumerable: true, get: function () { return HAMPState_1.HAMPState; } });
var HDSPModeErrors_1 = require("./models/HDSPModeErrors");
Object.defineProperty(exports, "HDSPModeErrors", { enumerable: true, get: function () { return HDSPModeErrors_1.HDSPModeErrors; } });
var HDSPResult_1 = require("./models/HDSPResult");
Object.defineProperty(exports, "HDSPResult", { enumerable: true, get: function () { return HDSPResult_1.HDSPResult; } });
var HSSPModeErrors_1 = require("./models/HSSPModeErrors");
Object.defineProperty(exports, "HSSPModeErrors", { enumerable: true, get: function () { return HSSPModeErrors_1.HSSPModeErrors; } });
var HSSPPlayResult_1 = require("./models/HSSPPlayResult");
Object.defineProperty(exports, "HSSPPlayResult", { enumerable: true, get: function () { return HSSPPlayResult_1.HSSPPlayResult; } });
var HSSPSetupResult_1 = require("./models/HSSPSetupResult");
Object.defineProperty(exports, "HSSPSetupResult", { enumerable: true, get: function () { return HSSPSetupResult_1.HSSPSetupResult; } });
var HSSPState_1 = require("./models/HSSPState");
Object.defineProperty(exports, "HSSPState", { enumerable: true, get: function () { return HSSPState_1.HSSPState; } });
var MAINTENANCEModeErrors_1 = require("./models/MAINTENANCEModeErrors");
Object.defineProperty(exports, "MAINTENANCEModeErrors", { enumerable: true, get: function () { return MAINTENANCEModeErrors_1.MAINTENANCEModeErrors; } });
var Mode_1 = require("./models/Mode");
Object.defineProperty(exports, "Mode", { enumerable: true, get: function () { return Mode_1.Mode; } });
var Model_1 = require("./models/Model");
Object.defineProperty(exports, "Model", { enumerable: true, get: function () { return Model_1.Model; } });
var ModeUpdateResponse_1 = require("./models/ModeUpdateResponse");
Object.defineProperty(exports, "ModeUpdateResponse", { enumerable: true, get: function () { return ModeUpdateResponse_1.ModeUpdateResponse; } });
var SlideResult_1 = require("./models/SlideResult");
Object.defineProperty(exports, "SlideResult", { enumerable: true, get: function () { return SlideResult_1.SlideResult; } });
var StateResult_1 = require("./models/StateResult");
Object.defineProperty(exports, "StateResult", { enumerable: true, get: function () { return StateResult_1.StateResult; } });
var UpdateStatusResponse_1 = require("./models/UpdateStatusResponse");
Object.defineProperty(exports, "UpdateStatusResponse", { enumerable: true, get: function () { return UpdateStatusResponse_1.UpdateStatusResponse; } });
var _BASEModeErrors_1 = require("./schemas/$BASEModeErrors");
Object.defineProperty(exports, "$BASEModeErrors", { enumerable: true, get: function () { return _BASEModeErrors_1.$BASEModeErrors; } });
var _Branch_1 = require("./schemas/$Branch");
Object.defineProperty(exports, "$Branch", { enumerable: true, get: function () { return _Branch_1.$Branch; } });
var _Connected_1 = require("./schemas/$Connected");
Object.defineProperty(exports, "$Connected", { enumerable: true, get: function () { return _Connected_1.$Connected; } });
var _ConnectedResponse_1 = require("./schemas/$ConnectedResponse");
Object.defineProperty(exports, "$ConnectedResponse", { enumerable: true, get: function () { return _ConnectedResponse_1.$ConnectedResponse; } });
var _ConnectionKey_1 = require("./schemas/$ConnectionKey");
Object.defineProperty(exports, "$ConnectionKey", { enumerable: true, get: function () { return _ConnectionKey_1.$ConnectionKey; } });
var _Duration_1 = require("./schemas/$Duration");
Object.defineProperty(exports, "$Duration", { enumerable: true, get: function () { return _Duration_1.$Duration; } });
var _ErrorResponse_1 = require("./schemas/$ErrorResponse");
Object.defineProperty(exports, "$ErrorResponse", { enumerable: true, get: function () { return _ErrorResponse_1.$ErrorResponse; } });
var _FirmwareStatus_1 = require("./schemas/$FirmwareStatus");
Object.defineProperty(exports, "$FirmwareStatus", { enumerable: true, get: function () { return _FirmwareStatus_1.$FirmwareStatus; } });
var _FirmwareVersion_1 = require("./schemas/$FirmwareVersion");
Object.defineProperty(exports, "$FirmwareVersion", { enumerable: true, get: function () { return _FirmwareVersion_1.$FirmwareVersion; } });
var _FixedPos_1 = require("./schemas/$FixedPos");
Object.defineProperty(exports, "$FixedPos", { enumerable: true, get: function () { return _FixedPos_1.$FixedPos; } });
var _GenericError_1 = require("./schemas/$GenericError");
Object.defineProperty(exports, "$GenericError", { enumerable: true, get: function () { return _GenericError_1.$GenericError; } });
var _GenericResult_1 = require("./schemas/$GenericResult");
Object.defineProperty(exports, "$GenericResult", { enumerable: true, get: function () { return _GenericResult_1.$GenericResult; } });
var _GenericResultResponse_1 = require("./schemas/$GenericResultResponse");
Object.defineProperty(exports, "$GenericResultResponse", { enumerable: true, get: function () { return _GenericResultResponse_1.$GenericResultResponse; } });
var _HAMPModeErrors_1 = require("./schemas/$HAMPModeErrors");
Object.defineProperty(exports, "$HAMPModeErrors", { enumerable: true, get: function () { return _HAMPModeErrors_1.$HAMPModeErrors; } });
var _HAMPResponse_1 = require("./schemas/$HAMPResponse");
Object.defineProperty(exports, "$HAMPResponse", { enumerable: true, get: function () { return _HAMPResponse_1.$HAMPResponse; } });
var _HAMPStartResponse_1 = require("./schemas/$HAMPStartResponse");
Object.defineProperty(exports, "$HAMPStartResponse", { enumerable: true, get: function () { return _HAMPStartResponse_1.$HAMPStartResponse; } });
var _HAMPState_1 = require("./schemas/$HAMPState");
Object.defineProperty(exports, "$HAMPState", { enumerable: true, get: function () { return _HAMPState_1.$HAMPState; } });
var _HAMPStopResponse_1 = require("./schemas/$HAMPStopResponse");
Object.defineProperty(exports, "$HAMPStopResponse", { enumerable: true, get: function () { return _HAMPStopResponse_1.$HAMPStopResponse; } });
var _HAMPVelocityPercent_1 = require("./schemas/$HAMPVelocityPercent");
Object.defineProperty(exports, "$HAMPVelocityPercent", { enumerable: true, get: function () { return _HAMPVelocityPercent_1.$HAMPVelocityPercent; } });
var _HAMPVelocityPercentResponse_1 = require("./schemas/$HAMPVelocityPercentResponse");
Object.defineProperty(exports, "$HAMPVelocityPercentResponse", { enumerable: true, get: function () { return _HAMPVelocityPercentResponse_1.$HAMPVelocityPercentResponse; } });
var _HardwareVersion_1 = require("./schemas/$HardwareVersion");
Object.defineProperty(exports, "$HardwareVersion", { enumerable: true, get: function () { return _HardwareVersion_1.$HardwareVersion; } });
var _HDSPModeErrors_1 = require("./schemas/$HDSPModeErrors");
Object.defineProperty(exports, "$HDSPModeErrors", { enumerable: true, get: function () { return _HDSPModeErrors_1.$HDSPModeErrors; } });
var _HDSPRequest_1 = require("./schemas/$HDSPRequest");
Object.defineProperty(exports, "$HDSPRequest", { enumerable: true, get: function () { return _HDSPRequest_1.$HDSPRequest; } });
var _HDSPResponse_1 = require("./schemas/$HDSPResponse");
Object.defineProperty(exports, "$HDSPResponse", { enumerable: true, get: function () { return _HDSPResponse_1.$HDSPResponse; } });
var _HDSPResult_1 = require("./schemas/$HDSPResult");
Object.defineProperty(exports, "$HDSPResult", { enumerable: true, get: function () { return _HDSPResult_1.$HDSPResult; } });
var _HDSPTimeRequest_1 = require("./schemas/$HDSPTimeRequest");
Object.defineProperty(exports, "$HDSPTimeRequest", { enumerable: true, get: function () { return _HDSPTimeRequest_1.$HDSPTimeRequest; } });
var _HSSPModeErrors_1 = require("./schemas/$HSSPModeErrors");
Object.defineProperty(exports, "$HSSPModeErrors", { enumerable: true, get: function () { return _HSSPModeErrors_1.$HSSPModeErrors; } });
var _HSSPPlay_1 = require("./schemas/$HSSPPlay");
Object.defineProperty(exports, "$HSSPPlay", { enumerable: true, get: function () { return _HSSPPlay_1.$HSSPPlay; } });
var _HSSPPlayResponse_1 = require("./schemas/$HSSPPlayResponse");
Object.defineProperty(exports, "$HSSPPlayResponse", { enumerable: true, get: function () { return _HSSPPlayResponse_1.$HSSPPlayResponse; } });
var _HSSPPlayResult_1 = require("./schemas/$HSSPPlayResult");
Object.defineProperty(exports, "$HSSPPlayResult", { enumerable: true, get: function () { return _HSSPPlayResult_1.$HSSPPlayResult; } });
var _HSSPResponse_1 = require("./schemas/$HSSPResponse");
Object.defineProperty(exports, "$HSSPResponse", { enumerable: true, get: function () { return _HSSPResponse_1.$HSSPResponse; } });
var _HSSPSetupResult_1 = require("./schemas/$HSSPSetupResult");
Object.defineProperty(exports, "$HSSPSetupResult", { enumerable: true, get: function () { return _HSSPSetupResult_1.$HSSPSetupResult; } });
var _HSSPState_1 = require("./schemas/$HSSPState");
Object.defineProperty(exports, "$HSSPState", { enumerable: true, get: function () { return _HSSPState_1.$HSSPState; } });
var _InfoResponse_1 = require("./schemas/$InfoResponse");
Object.defineProperty(exports, "$InfoResponse", { enumerable: true, get: function () { return _InfoResponse_1.$InfoResponse; } });
var _Looping_1 = require("./schemas/$Looping");
Object.defineProperty(exports, "$Looping", { enumerable: true, get: function () { return _Looping_1.$Looping; } });
var _LoopSettingResponse_1 = require("./schemas/$LoopSettingResponse");
Object.defineProperty(exports, "$LoopSettingResponse", { enumerable: true, get: function () { return _LoopSettingResponse_1.$LoopSettingResponse; } });
var _LoopSettingUpdate_1 = require("./schemas/$LoopSettingUpdate");
Object.defineProperty(exports, "$LoopSettingUpdate", { enumerable: true, get: function () { return _LoopSettingUpdate_1.$LoopSettingUpdate; } });
var _MAINTENANCEModeErrors_1 = require("./schemas/$MAINTENANCEModeErrors");
Object.defineProperty(exports, "$MAINTENANCEModeErrors", { enumerable: true, get: function () { return _MAINTENANCEModeErrors_1.$MAINTENANCEModeErrors; } });
var _Mode_1 = require("./schemas/$Mode");
Object.defineProperty(exports, "$Mode", { enumerable: true, get: function () { return _Mode_1.$Mode; } });
var _Model_1 = require("./schemas/$Model");
Object.defineProperty(exports, "$Model", { enumerable: true, get: function () { return _Model_1.$Model; } });
var _ModeUpdate_1 = require("./schemas/$ModeUpdate");
Object.defineProperty(exports, "$ModeUpdate", { enumerable: true, get: function () { return _ModeUpdate_1.$ModeUpdate; } });
var _ModeUpdateResponse_1 = require("./schemas/$ModeUpdateResponse");
Object.defineProperty(exports, "$ModeUpdateResponse", { enumerable: true, get: function () { return _ModeUpdateResponse_1.$ModeUpdateResponse; } });
var _NextXAT_1 = require("./schemas/$NextXAT");
Object.defineProperty(exports, "$NextXAT", { enumerable: true, get: function () { return _NextXAT_1.$NextXAT; } });
var _NextXAVA_1 = require("./schemas/$NextXAVA");
Object.defineProperty(exports, "$NextXAVA", { enumerable: true, get: function () { return _NextXAVA_1.$NextXAVA; } });
var _NextXPT_1 = require("./schemas/$NextXPT");
Object.defineProperty(exports, "$NextXPT", { enumerable: true, get: function () { return _NextXPT_1.$NextXPT; } });
var _NextXPVA_1 = require("./schemas/$NextXPVA");
Object.defineProperty(exports, "$NextXPVA", { enumerable: true, get: function () { return _NextXPVA_1.$NextXPVA; } });
var _NextXPVP_1 = require("./schemas/$NextXPVP");
Object.defineProperty(exports, "$NextXPVP", { enumerable: true, get: function () { return _NextXPVP_1.$NextXPVP; } });
var _Offset_1 = require("./schemas/$Offset");
Object.defineProperty(exports, "$Offset", { enumerable: true, get: function () { return _Offset_1.$Offset; } });
var _OffsetResponse_1 = require("./schemas/$OffsetResponse");
Object.defineProperty(exports, "$OffsetResponse", { enumerable: true, get: function () { return _OffsetResponse_1.$OffsetResponse; } });
var _OffsetUpdate_1 = require("./schemas/$OffsetUpdate");
Object.defineProperty(exports, "$OffsetUpdate", { enumerable: true, get: function () { return _OffsetUpdate_1.$OffsetUpdate; } });
var _OtaLatest_1 = require("./schemas/$OtaLatest");
Object.defineProperty(exports, "$OtaLatest", { enumerable: true, get: function () { return _OtaLatest_1.$OtaLatest; } });
var _OtaLatestResponse_1 = require("./schemas/$OtaLatestResponse");
Object.defineProperty(exports, "$OtaLatestResponse", { enumerable: true, get: function () { return _OtaLatestResponse_1.$OtaLatestResponse; } });
var _Outliers_1 = require("./schemas/$Outliers");
Object.defineProperty(exports, "$Outliers", { enumerable: true, get: function () { return _Outliers_1.$Outliers; } });
var _PercentValue_1 = require("./schemas/$PercentValue");
Object.defineProperty(exports, "$PercentValue", { enumerable: true, get: function () { return _PercentValue_1.$PercentValue; } });
var _PositionAbsolute_1 = require("./schemas/$PositionAbsolute");
Object.defineProperty(exports, "$PositionAbsolute", { enumerable: true, get: function () { return _PositionAbsolute_1.$PositionAbsolute; } });
var _PositionAbsoluteResponse_1 = require("./schemas/$PositionAbsoluteResponse");
Object.defineProperty(exports, "$PositionAbsoluteResponse", { enumerable: true, get: function () { return _PositionAbsoluteResponse_1.$PositionAbsoluteResponse; } });
var _RPCResult_1 = require("./schemas/$RPCResult");
Object.defineProperty(exports, "$RPCResult", { enumerable: true, get: function () { return _RPCResult_1.$RPCResult; } });
var _ServerTimeResponse_1 = require("./schemas/$ServerTimeResponse");
Object.defineProperty(exports, "$ServerTimeResponse", { enumerable: true, get: function () { return _ServerTimeResponse_1.$ServerTimeResponse; } });
var _SessionId_1 = require("./schemas/$SessionId");
Object.defineProperty(exports, "$SessionId", { enumerable: true, get: function () { return _SessionId_1.$SessionId; } });
var _SettingsResponse_1 = require("./schemas/$SettingsResponse");
Object.defineProperty(exports, "$SettingsResponse", { enumerable: true, get: function () { return _SettingsResponse_1.$SettingsResponse; } });
var _Setup_1 = require("./schemas/$Setup");
Object.defineProperty(exports, "$Setup", { enumerable: true, get: function () { return _Setup_1.$Setup; } });
var _Sha256_1 = require("./schemas/$Sha256");
Object.defineProperty(exports, "$Sha256", { enumerable: true, get: function () { return _Sha256_1.$Sha256; } });
var _SlideResponse_1 = require("./schemas/$SlideResponse");
Object.defineProperty(exports, "$SlideResponse", { enumerable: true, get: function () { return _SlideResponse_1.$SlideResponse; } });
var _SlideResult_1 = require("./schemas/$SlideResult");
Object.defineProperty(exports, "$SlideResult", { enumerable: true, get: function () { return _SlideResult_1.$SlideResult; } });
var _SlideResultResponse_1 = require("./schemas/$SlideResultResponse");
Object.defineProperty(exports, "$SlideResultResponse", { enumerable: true, get: function () { return _SlideResultResponse_1.$SlideResultResponse; } });
var _SliderMaxResponse_1 = require("./schemas/$SliderMaxResponse");
Object.defineProperty(exports, "$SliderMaxResponse", { enumerable: true, get: function () { return _SliderMaxResponse_1.$SliderMaxResponse; } });
var _SliderMinResponse_1 = require("./schemas/$SliderMinResponse");
Object.defineProperty(exports, "$SliderMinResponse", { enumerable: true, get: function () { return _SliderMinResponse_1.$SliderMinResponse; } });
var _SlideSettings_1 = require("./schemas/$SlideSettings");
Object.defineProperty(exports, "$SlideSettings", { enumerable: true, get: function () { return _SlideSettings_1.$SlideSettings; } });
var _SlideUpdateResponse_1 = require("./schemas/$SlideUpdateResponse");
Object.defineProperty(exports, "$SlideUpdateResponse", { enumerable: true, get: function () { return _SlideUpdateResponse_1.$SlideUpdateResponse; } });
var _StateResult_1 = require("./schemas/$StateResult");
Object.defineProperty(exports, "$StateResult", { enumerable: true, get: function () { return _StateResult_1.$StateResult; } });
var _StatusResponse_1 = require("./schemas/$StatusResponse");
Object.defineProperty(exports, "$StatusResponse", { enumerable: true, get: function () { return _StatusResponse_1.$StatusResponse; } });
var _SyncCount_1 = require("./schemas/$SyncCount");
Object.defineProperty(exports, "$SyncCount", { enumerable: true, get: function () { return _SyncCount_1.$SyncCount; } });
var _SyncResponse_1 = require("./schemas/$SyncResponse");
Object.defineProperty(exports, "$SyncResponse", { enumerable: true, get: function () { return _SyncResponse_1.$SyncResponse; } });
var _Timestamp_1 = require("./schemas/$Timestamp");
Object.defineProperty(exports, "$Timestamp", { enumerable: true, get: function () { return _Timestamp_1.$Timestamp; } });
var _UpdatePerform_1 = require("./schemas/$UpdatePerform");
Object.defineProperty(exports, "$UpdatePerform", { enumerable: true, get: function () { return _UpdatePerform_1.$UpdatePerform; } });
var _UpdateStatusResponse_1 = require("./schemas/$UpdateStatusResponse");
Object.defineProperty(exports, "$UpdateStatusResponse", { enumerable: true, get: function () { return _UpdateStatusResponse_1.$UpdateStatusResponse; } });
var _Url_1 = require("./schemas/$Url");
Object.defineProperty(exports, "$Url", { enumerable: true, get: function () { return _Url_1.$Url; } });
var _VelocityAbsolute_1 = require("./schemas/$VelocityAbsolute");
Object.defineProperty(exports, "$VelocityAbsolute", { enumerable: true, get: function () { return _VelocityAbsolute_1.$VelocityAbsolute; } });
var BaseService_1 = require("./services/BaseService");
Object.defineProperty(exports, "BaseService", { enumerable: true, get: function () { return BaseService_1.BaseService; } });
var HampService_1 = require("./services/HampService");
Object.defineProperty(exports, "HampService", { enumerable: true, get: function () { return HampService_1.HampService; } });
var HdspService_1 = require("./services/HdspService");
Object.defineProperty(exports, "HdspService", { enumerable: true, get: function () { return HdspService_1.HdspService; } });
var HsspService_1 = require("./services/HsspService");
Object.defineProperty(exports, "HsspService", { enumerable: true, get: function () { return HsspService_1.HsspService; } });
var HstpService_1 = require("./services/HstpService");
Object.defineProperty(exports, "HstpService", { enumerable: true, get: function () { return HstpService_1.HstpService; } });
var MaintenanceService_1 = require("./services/MaintenanceService");
Object.defineProperty(exports, "MaintenanceService", { enumerable: true, get: function () { return MaintenanceService_1.MaintenanceService; } });
var OtaService_1 = require("./services/OtaService");
Object.defineProperty(exports, "OtaService", { enumerable: true, get: function () { return OtaService_1.OtaService; } });
var SlideService_1 = require("./services/SlideService");
Object.defineProperty(exports, "SlideService", { enumerable: true, get: function () { return SlideService_1.SlideService; } });
var TimesyncService_1 = require("./services/TimesyncService");
Object.defineProperty(exports, "TimesyncService", { enumerable: true, get: function () { return TimesyncService_1.TimesyncService; } });
